version: '3.4'

services:
    
  bookit.frontend:
    image: ${DOCKER_REGISTRY-}bookitfrontend
    build:
      context: .
      dockerfile: src/BookIt.Frontend/Dockerfile
    environment:
      CONNECTION_STRING: "Host=postgres;Port=5432;Database=postgres;Username=admin;Password=root;Integrated Security=true;Pooling=true;"


  bookit.api:
    image: ${DOCKER_REGISTRY-}bookitapi
    build:
      context: .
      dockerfile: src/BookIt.API/Dockerfile
    environment:
       CONNECTION_STRING: "Host=postgres;Port=5432;Database=postgres;Username=admin;Password=root;Integrated Security=true;Pooling=true;"

  postgres:
    image: postgres:alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    image: dcagatay/pwless-pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - 15432:80
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      # POSTGRES_HOST: "postgres"
      # POSTGRES_PORT: "5432"
      # POSTGRES_DB: "*"
    restart: unless-stopped

volumes:
  postgres-data:
